namespace PetBox.Core.Auth;

// THE ALLOWLIST — the one list that drives BOTH the ratchet (AuthzDeclarationRatchetTests) and the
// two enforcement points (TenantEnforcementMiddleware, McpTenantEnforcementFilter).
//
// It lives in PRODUCT code, not in the test, and that is a requirement of the work card rather than
// tidiness: "Один список управляет и тестом, и энфорсом — разойтись не могут". Two lists would drift
// the first time somebody crossed a line out of one of them — and the failure is silent in the worse
// direction. A surface removed from the ENFORCEMENT copy but left in the ratchet's copy is a surface
// the ratchet still calls "known debt" while the PEP has already started refusing it; the reverse is
// a surface the ratchet demands a declaration for while the PEP lets everything through. The list is
// the rollout mechanism itself ("Роллаут = вычёркивание из allowlist, а не отдельный флаг"), so it
// has to be the same object on both sides.
//
// WHAT AN ENTRY MEANS: this surface predates the rule. The PEP passes it through untouched, and the
// ratchet does not demand a declaration for it. It is NOT a statement that the surface is fine — it
// is the debt this work item exists to pay off, made countable.
//
// IT ONLY EVER SHRINKS. A stale entry (a surface that has since been declared, or that no longer
// exists) fails AuthzDeclarationRatchetTests.StaleAllowlistEntries_AreDeleted, so the list cannot
// silently re-grant an exemption to whoever edits that surface next. A NEW surface never goes in
// here: it declares [TenantFrom]/[TenantExempt] like everything written after the rule.
//
// GENERATED BY THE INVENTORY, never by hand — AuthzDeclarationRatchetTests.TheInventory_IsMachineReadable
// writes these same keys to .tmp/authz-surface-inventory.txt. Three independent human counts of the
// MCP tool surface alone came back 92 / 100 / 122, so a hand-written list of this size is exactly the
// human count the work card forbids.
public static class TenantEnforcementAllowlist
{
	// It STARTED at 217 surfaces: 55 REST + 65 Razor pages + 97 MCP tools — the whole tree at the
	// moment the enforcement points were written, which is why enabling them changed behaviour on NONE
	// of them. It shrinks one FAMILY at a time (work `authz-default-deny-delivery`, step 5); the MCP
	// wave took all 97 tools out, leaving the endpoint plane for its own waves. The live count is never
	// a comment — run AuthzDeclarationRatchetTests and read .tmp/authz-surface-inventory.txt.
	public static IReadOnlySet<string> Keys { get; } = new HashSet<string>(StringComparer.Ordinal)
	{
		// REST — 55 minimal-API endpoints (METHOD + route pattern, as the caller addresses them).
		"rest:DELETE /api/config/{workspaceKey}/bindings",
		"rest:DELETE /api/data/{projectKey}/dbs/{name}",
		"rest:DELETE /api/logs/{projectKey}/logs/{name}",
		"rest:DELETE /api/sessions/{projectKey}/{sessionId}",
		"rest:DELETE /api/{projectKey}/agent-defs/{key}",
		"rest:GET /.well-known/oauth-authorization-server",
		"rest:GET /.well-known/oauth-authorization-server/{*rest}",
		"rest:GET /.well-known/oauth-protected-resource",
		"rest:GET /.well-known/oauth-protected-resource/{*rest}",
		"rest:GET /.well-known/openid-configuration",
		"rest:GET /.well-known/openid-configuration/{*rest}",
		"rest:GET /agent/poll",
		"rest:GET /api/auth/validate",
		"rest:GET /api/data/{projectKey}/dbs",
		"rest:GET /api/data/{projectKey}/{dbName}/migrations",
		"rest:GET /api/logs/{projectKey}/logs",
		"rest:GET /api/logs/{projectKey}/{logName}/live-tail",
		"rest:GET /api/logs/{projectKey}/{logName}/query",
		"rest:GET /api/logs/{projectKey}/{logName}/services",
		"rest:GET /api/memory/{projectKey}/canon",
		"rest:GET /api/sessions/{projectKey}",
		"rest:GET /api/share/{token}/tsv",
		"rest:GET /api/{projectKey}/agent-defs",
		"rest:GET /api/{projectKey}/agent-defs/{key}",
		"rest:GET /openapi/{documentName}.json",
		"rest:GET /v1/conf",
		"rest:GET|HEAD /health",
		"rest:GET|HEAD /version",
		"rest:POST /agent/heartbeat",
		"rest:POST /api/auth/logout",
		"rest:POST /api/config/{workspaceKey}/bindings",
		"rest:POST /api/data/{projectKey}/dbs",
		"rest:POST /api/data/{projectKey}/{dbName}/exec",
		"rest:POST /api/data/{projectKey}/{dbName}/query",
		"rest:POST /api/data/{projectKey}/{dbName}/schema",
		"rest:POST /api/deploy/nodes",
		"rest:POST /api/events/raw",
		"rest:POST /api/health",
		"rest:POST /api/ingest/{projectKey}/{logName}/clef",
		"rest:POST /api/ingest/{projectKey}/{logName}/compat/seq/api/events/raw",
		"rest:POST /api/logs/{projectKey}/logs",
		"rest:POST /api/sessions/{projectKey}/{sessionId}",
		"rest:POST /api/sessions/{projectKey}/{sessionId}/append",
		"rest:POST /api/share",
		"rest:POST /api/ui/board-filter-prefs",
		"rest:POST /api/ui/project",
		"rest:POST /api/ui/workspace",
		"rest:POST /v1/chat/completions",
		"rest:POST /v1/logs",
		"rest:POST /v1/logs/{projectKey}/{logName}",
		"rest:POST /v1/metrics",
		"rest:POST /v1/metrics/{projectKey}/{logName}",
		"rest:POST /v1/traces",
		"rest:POST /v1/traces/{projectKey}/{logName}",
		"rest:PUT /api/{projectKey}/agent-defs/{key}",
	
		// RAZOR — 65 pages (one entry per page, not per endpoint: the PageModel CLASS is the carrier).
		"page:/AccessDenied",
		"page:/Admin/AgentKeys",
		"page:/Admin/Deploy",
		"page:/Admin/Index",
		"page:/Admin/ProjectAgentDefs",
		"page:/Admin/ProjectConnect",
		"page:/Admin/ProjectData",
		"page:/Admin/ProjectDataDb",
		"page:/Admin/ProjectDetail",
		"page:/Admin/ProjectKeys",
		"page:/Admin/ProjectLogSettings",
		"page:/Admin/ProjectLogs",
		"page:/Admin/ProjectMemory",
		"page:/Admin/ProjectMethodology",
		"page:/Admin/ProjectSettingsAdmin",
		"page:/Admin/ProjectTasks",
		"page:/Admin/Projects",
		"page:/Admin/SysDefaults",
		"page:/Admin/Users",
		"page:/Admin/WorkspaceAdmin",
		"page:/Admin/WorkspaceAgentKeys",
		"page:/Admin/WorkspaceDefaults",
		"page:/Admin/WorkspaceDetail",
		"page:/Admin/WorkspaceSettings",
		"page:/Admin/WorkspaceUsers",
		"page:/Admin/Workspaces",
		"page:/Config/Editor",
		"page:/Config/History",
		"page:/Config/Index",
		"page:/Config/Preview",
		"page:/Config/Tags",
		"page:/Dashboard/Index",
		"page:/Doc/Agent",
		"page:/Doc/Index",
		"page:/Doc/Methodology",
		"page:/Doc/Onboarding",
		"page:/Doc/Overview",
		"page:/Doc/Philosophy",
		"page:/Doc/Wire",
		"page:/Error",
		"page:/Index",
		"page:/Llm/Index",
		"page:/Login",
		"page:/Logs/EventDetails",
		"page:/Logs/Index",
		"page:/Logs/Trace",
		"page:/Logs/Traces",
		"page:/Me/Account",
		"page:/Me/NewWorkspace",
		"page:/Me/Preferences",
		"page:/Me/Security",
		"page:/Nav/Tree",
		"page:/ProjectHome/Database",
		"page:/ProjectHome/Databases",
		"page:/ProjectHome/Index",
		"page:/ProjectHome/Memory",
		"page:/ProjectHome/MemoryStore",
		"page:/ProjectHome/Session",
		"page:/ProjectHome/Sessions",
		"page:/ProjectHome/Table",
		"page:/ProjectHome/TaskBoard",
		"page:/ProjectHome/TaskBoardNode",
		"page:/ProjectHome/Tasks",
		"page:/Search",
		"page:/Share",
	
		// MCP — the 97 tools this list used to hold. THIS was the number the work card asked for: three
		// independent human counts said 92 / 100 / 122, and none of them was right; 97 is cross-checked
		// in TheMcpSweep_MatchesTheToolsTheServerActuallyRegisters against the McpServerTool instances a
		// running host has in DI — i.e. against what the server actually serves, not a second count.
		//
		// Every one of them is now DECLARED on its [McpServerToolType] class ([TenantFrom] for the 74
		// that name a tenant, [TenantExempt] for the 23 that belong to a closed exemption class) and
		// enforced by McpTenantEnforcementFilter. Nothing from the MCP plane may come back here: a NEW
		// tool declares like the rest.
		"mcp:data_exec",
		"mcp:data_query",
		"mcp:data_schema_apply",
		"mcp:db_create",
		"mcp:db_delete",
		"mcp:db_describe",
		"mcp:db_list",
		"mcp:health_search",
		"mcp:llm_chat",
		"mcp:llm_config_get",
		"mcp:llm_config_upsert",
		"mcp:llm_embed",
		"mcp:llm_rerank",
		"mcp:log_create",
		"mcp:log_delete",
		"mcp:log_list",
		"mcp:log_query",
		"mcp:log_update",
		"mcp:memory_delta",
		"mcp:memory_get",
		"mcp:memory_remember",
		"mcp:memory_search",
		"mcp:memory_store_create",
		"mcp:memory_store_delete",
		"mcp:memory_store_list",
		"mcp:memory_upsert",
		"mcp:relations_create",
		"mcp:relations_delete",
		"mcp:relations_list",
		"mcp:search_reindex",
		"mcp:session_append",
		"mcp:session_delete",
		"mcp:session_delta",
		"mcp:session_get",
		"mcp:session_search",
		"mcp:session_upsert",
		"mcp:tasks_board_adopt",
		"mcp:tasks_board_close",
		"mcp:tasks_board_create",
		"mcp:tasks_board_delete",
		"mcp:tasks_board_list",
		"mcp:tasks_board_reopen",
		"mcp:tasks_board_set_wire",
		"mcp:tasks_delta",
		"mcp:tasks_methodology_active_get",
		"mcp:tasks_methodology_close",
		"mcp:tasks_methodology_create",
		"mcp:tasks_methodology_describe",
		"mcp:tasks_methodology_get",
		"mcp:tasks_methodology_guide",
		"mcp:tasks_methodology_list",
		"mcp:tasks_methodology_rules_get",
		"mcp:tasks_methodology_rules_upsert",
		"mcp:tasks_methodology_set_active",
		"mcp:tasks_methodology_template_delete",
		"mcp:tasks_methodology_template_get",
		"mcp:tasks_methodology_template_list",
		"mcp:tasks_methodology_template_snapshot",
		"mcp:tasks_methodology_template_upsert",
		"mcp:tasks_methodology_utility_get",
		"mcp:tasks_methodology_utility_upsert",
		"mcp:tasks_node_get",
		"mcp:tasks_search",
		"mcp:tasks_upsert",
		"mcp:tasks_workflow",
	};

	// The question both PEPs ask, once per call, before they look at a declaration at all.
	public static bool Contains(string surfaceKey) => Keys.Contains(surfaceKey);
}
