namespace PetBox.Core.Auth;

// THE ALLOWLIST — the one list that drives BOTH the ratchet (AuthzDeclarationRatchetTests) and the
// two enforcement points (TenantEnforcementMiddleware, McpTenantEnforcementFilter).
//
// It lives in PRODUCT code, not in the test, and that is a requirement of the work card rather than
// tidiness: "Один список управляет и тестом, и энфорсом — разойтись не могут". Two lists would drift
// the first time somebody crossed a line out of one of them — and the failure is silent in the worse
// direction. A surface removed from the ENFORCEMENT copy but left in the ratchet's copy is a surface
// the ratchet still calls "known debt" while the PEP has already started refusing it; the reverse is
// a surface the ratchet demands a declaration for while the PEP lets everything through. The list is
// the rollout mechanism itself ("Роллаут = вычёркивание из allowlist, а не отдельный флаг"), so it
// has to be the same object on both sides.
//
// WHAT AN ENTRY MEANS: this surface predates the rule. The PEP passes it through untouched, and the
// ratchet does not demand a declaration for it. It is NOT a statement that the surface is fine — it
// is the debt this work item exists to pay off, made countable.
//
// IT ONLY EVER SHRINKS. A stale entry (a surface that has since been declared, or that no longer
// exists) fails AuthzDeclarationRatchetTests.StaleAllowlistEntries_AreDeleted, so the list cannot
// silently re-grant an exemption to whoever edits that surface next. A NEW surface never goes in
// here: it declares [TenantFrom]/[TenantExempt] like everything written after the rule.
//
// GENERATED BY THE INVENTORY, never by hand — AuthzDeclarationRatchetTests.TheInventory_IsMachineReadable
// writes these same keys to .tmp/authz-surface-inventory.txt. Three independent human counts of the
// MCP tool surface alone came back 92 / 100 / 122, so a hand-written list of this size is exactly the
// human count the work card forbids.
public static class TenantEnforcementAllowlist
{
	// It STARTED at 217 surfaces: 55 REST + 65 Razor pages + 97 MCP tools — the whole tree at the
	// moment the enforcement points were written, which is why enabling them changed behaviour on NONE
	// of them. It shrinks one FAMILY at a time (work `authz-default-deny-delivery`, step 5); the MCP
	// wave took ALL 97 tools out and the REST wave all but two of the 55, so what is left below is the
	// Razor plane plus the two Seq-header-authenticated ingest routes. The live count is never a
	// comment: run AuthzDeclarationRatchetTests and read .tmp/authz-surface-inventory.txt.
	public static IReadOnlySet<string> Keys { get; } = new HashSet<string>(StringComparer.Ordinal)
	{
		// REST — TWO of the original 55 (METHOD + route pattern, as the caller addresses them). The other
		// 53 declare, and the accounting is in the note at the bottom of this list.
		//
		// THE TWO THAT STAY, and the reason, written HERE rather than remembered — the same discipline
		// memory_get was left under during the MCP wave.
		//
		// Both are `.AllowAnonymous()` and authenticate a Seq-protocol key out of the X-Seq-ApiKey
		// HEADER by hand (IApiKeyLookup), because a stock Seq client sends no X-Api-Key and so cannot go
		// through the ApiKey SCHEME. That means there is NO ClaimsPrincipal on these requests:
		// HttpContext.User is unauthenticated by the time TenantEnforcementMiddleware runs, and
		// ITenantAuthorizer answers NotAuthorized for an unauthenticated principal — so declaring
		// [TenantFrom(Route, "projectKey")] here would 403 EVERY Seq ingest, including the legitimate
		// ones. Declaring an exemption instead would be a lie: these routes have a real tenant and a
		// real per-call check.
		//
		// So the manual check STAYS, and it is a complete one: both handlers run
		// ProjectScope.EvaluateAsync with the key ROW's own ProjectKey/SandboxOnly, i.e. the same claim
		// identity + sandbox containment the middleware would apply. The cross-tenant probe measures
		// both as Denied. What is missing is not the check but the PRINCIPAL — closing that means
		// authenticating the Seq header into a ClaimsPrincipal (a real auth change, its own work item),
		// not a line in this wave.
		"rest:POST /api/events/raw",
		"rest:POST /api/ingest/{projectKey}/{logName}/compat/seq/api/events/raw",
	
		// RAZOR — what is LEFT of the 65 (one entry per page, not per endpoint: the PageModel CLASS is
		// the carrier). The Razor wave takes them out one family at a time; the accounting of what has
		// already gone is in the note at the bottom of this list.
		"page:/AccessDenied",
		"page:/Admin/AgentKeys",
		"page:/Admin/Deploy",
		"page:/Admin/Index",
		"page:/Admin/ProjectAgentDefs",
		"page:/Admin/ProjectConnect",
		"page:/Admin/ProjectData",
		"page:/Admin/ProjectDataDb",
		"page:/Admin/ProjectDetail",
		"page:/Admin/ProjectKeys",
		"page:/Admin/ProjectLogSettings",
		"page:/Admin/ProjectLogs",
		"page:/Admin/ProjectMemory",
		"page:/Admin/ProjectMethodology",
		"page:/Admin/ProjectSettingsAdmin",
		"page:/Admin/ProjectTasks",
		"page:/Admin/Projects",
		"page:/Admin/SysDefaults",
		"page:/Admin/Users",
		"page:/Admin/WorkspaceAdmin",
		"page:/Admin/WorkspaceAgentKeys",
		"page:/Admin/WorkspaceDefaults",
		"page:/Admin/WorkspaceDetail",
		"page:/Admin/WorkspaceSettings",
		"page:/Admin/WorkspaceUsers",
		"page:/Admin/Workspaces",
		"page:/Config/Editor",
		"page:/Config/History",
		"page:/Config/Index",
		"page:/Config/Preview",
		"page:/Config/Tags",
		"page:/Dashboard/Index",
		"page:/Index",
		"page:/Llm/Index",
		"page:/Logs/EventDetails",
		"page:/Logs/Index",
		"page:/Logs/Trace",
		"page:/Logs/Traces",
		"page:/Me/Account",
		"page:/Me/NewWorkspace",
		"page:/Me/Preferences",
		"page:/Me/Security",
		"page:/Nav/Tree",
		"page:/ProjectHome/Database",
		"page:/ProjectHome/Databases",
		"page:/ProjectHome/Index",
		"page:/ProjectHome/Memory",
		"page:/ProjectHome/MemoryStore",
		"page:/ProjectHome/Session",
		"page:/ProjectHome/Sessions",
		"page:/ProjectHome/Table",
		"page:/ProjectHome/TaskBoard",
		"page:/ProjectHome/TaskBoardNode",
		"page:/ProjectHome/Tasks",
		"page:/Search",
		"page:/Share",
	
		// REST — 53 of 55 GONE, in the REST wave (work `authz-default-deny-delivery`, step 5), one family
		// per commit. The split, all of it machine-readable in .tmp/authz-surface-inventory.txt:
		//   * 34 declare a tenant — 26 [TenantFrom(Route, "projectKey")], 2
		//     [TenantFrom(Route, "workspaceKey", TenantKind.Workspace)] (the config bindings verbs), 2
		//     [TenantFrom(BodyField, …)] on a project (/api/share's `projectKey`, /api/health's nested
		//     `tags.project`), 2 [TenantFrom(BodyField, "ws", TenantKind.Workspace)] on a FORM field (the
		//     two /api/ui switches) and 2 [TenantFrom(CallerDefault)] (/v1/conf, /v1/chat/completions);
		//   * 19 are [TenantExempt] — 9 public, 4 capability-token, 3 fleet-wide, 3 identity.
		// About 34 hand-written project/workspace checks came out with them, and two files that existed
		// only to hold one (PetBox.Data's DataAuth, ConfigApi's AuthorizeWorkspaceAsync) are gone.
		//
		// The two above are the only REST entries left, and they are NOT "the ones nobody got to": they
		// are the ones a declaration cannot yet express, for the reason written beside them.

		// MCP — NOTHING. All 97 tools left this list in the declaration wave (work
		// `authz-default-deny-delivery`, step 5) and the whole plane is enforced by
		// McpTenantEnforcementFilter.
		//
		// 97 was the number the work card asked for: three independent human counts said 92 / 100 / 122
		// and none of them was right. It is cross-checked in
		// TheMcpSweep_MatchesTheToolsTheServerActuallyRegisters against the McpServerTool instances a
		// running host has in DI — against what the server actually serves, not against a second count.
		//
		// The split, all of it machine-readable in .tmp/authz-surface-inventory.txt:
		//   * 74 declare a tenant — 66 [TenantFrom(Argument, "projectKey")], plus the 8 memory_* verbs on
		//     [TenantFrom(ArgumentOrContainer, "projectKey")], whose projectKey carries either a project
		//     key or a `$workspace`/`$ws-<key>` shared-memory container;
		//   * 23 are [TenantExempt] — 11 provisioning, 9 fleet-wide, 2 identity, 1 feedback.
		//
		// A NEW tool declares like the rest. Nothing from this plane may come back here: the entries
		// above are surfaces that PREDATE the rule, and the ratchet fails a stale one.
	};

	// The question both PEPs ask, once per call, before they look at a declaration at all.
	public static bool Contains(string surfaceKey) => Keys.Contains(surfaceKey);
}
