// The single git policy for kit-managed paths: they belong in the PROJECT's `.gitignore`
// (card: normalize-all-environments-to-default, item 5 — owner decision 2026-09-02).
//
// The alternative that was rejected, on the record: `.git/info/exclude` would keep another
// person's repository byte-for-byte untouched, which is the safer default and was recommended.
// The owner chose the visible variant deliberately — an exclude rule nobody can see in a diff is
// a policy nobody knows exists, and these files land in repositories other people work in.
//
// What makes writing into someone else's `.gitignore` acceptable is the block discipline below:
// everything the kit owns lives between two literal marker lines, the ONLY region this module
// ever reads or replaces. Lines outside it are copied through byte for byte — the file is never
// re-serialized, re-sorted, or de-duplicated. A project that deletes the block gets it back on
// the next apply; a project that edits lines inside it loses those edits, which is exactly what
// "managed" means everywhere else in this kit.
//
// Plain TS for native node type-stripping: zero deps.

import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname } from "node:path";

export const GITIGNORE_BEGIN = "# >>> petbox-wire managed paths (petbox: managed) >>>";
export const GITIGNORE_END = "# <<< petbox-wire managed paths <<<";

const BLOCK_NOTE =
  "# Generated by petbox-wire. Edits inside this block are overwritten on the next `apply`.";

/** The exact text of the block for `entries` — no trailing newline, joined with "\n". */
export function renderGitignoreBlock(entries: readonly string[]): string {
  return [GITIGNORE_BEGIN, BLOCK_NOTE, ...entries, GITIGNORE_END].join("\n");
}

export type GitignoreOutcome = "new" | "updated" | "unchanged";

/**
 * Compute the full new content of `.gitignore` given its current content (null = no file yet).
 * Pure — the filesystem lives in upsertGitignoreBlock below, so the splice logic is testable
 * without a temp directory and, more importantly, so "what changes" can be asserted against
 * hand-written awkward inputs (CRLF, no trailing newline, a block already at the top).
 */
export function spliceGitignoreBlock(current: string | null, entries: readonly string[]): string {
  const block = renderGitignoreBlock(entries);
  if (current === null || current.trim() === "") return block + "\n";

  const eol = current.includes("\r\n") ? "\r\n" : "\n";
  const lines = current.split(/\r?\n/);
  const begin = lines.indexOf(GITIGNORE_BEGIN);
  const end = lines.indexOf(GITIGNORE_END);
  const blockLines = block.split("\n");

  if (begin !== -1 && end !== -1 && end > begin) {
    const next = [...lines.slice(0, begin), ...blockLines, ...lines.slice(end + 1)];
    return next.join(eol);
  }
  // No block yet — append it, separated by exactly one blank line from whatever is already there.
  const body = current.replace(/\r?\n+$/, "");
  return [body, "", ...blockLines].join(eol) + eol;
}

/**
 * Write the managed block into `absPath`. Returns what happened; `dryRun` computes the identical
 * verdict without touching the disk (same contract as apply-write.ts's writeArtifact, and for the
 * same reason: a preview and a real run must never be able to disagree).
 */
export function upsertGitignoreBlock(
  absPath: string,
  entries: readonly string[],
  opts: { readonly dryRun?: boolean } = {},
): GitignoreOutcome {
  let current: string | null = null;
  if (existsSync(absPath)) {
    try {
      current = readFileSync(absPath, "utf8");
    } catch {
      current = null; // unreadable — treat as absent; the write below will surface the real error
    }
  }
  const next = spliceGitignoreBlock(current, entries);
  if (current !== null && current === next) return "unchanged";
  if (!opts.dryRun) {
    mkdirSync(dirname(absPath), { recursive: true });
    writeFileSync(absPath, next, "utf8");
  }
  return current === null ? "new" : "updated";
}
