// POSIX half of persistKeyForAgents (see wire.ts) — split into its own side-effect-free module
// (no top-level main()) so it can be imported directly by tests without triggering the CLI.
// wire.ts is NOT import-safe: it runs main() at module top level (see bin/petbox-wire.js), so a
// test must not `import` it — this file exists to give the logic a testable home.

import { appendFileSync, chmodSync, existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";

function readJson(path: string): any {
  try {
    return JSON.parse(readFileSync(path, "utf8"));
  } catch {
    return null;
  }
}

// Regenerate <homeDir>/.petbox/env.sh from the whole key store and ensure a login shell will
// source it. Parameterized on homeDir (instead of reading os.homedir() directly) so tests can
// point it at a throwaway tmp dir rather than touching the real $HOME. Returns the path written,
// for the caller's log message.
export function persistKeyForAgentsPosix(homeDir: string): string {
  const store = readJson(join(homeDir, ".petbox", "keys.json")) ?? {};
  const lines = Object.entries(store)
    .filter(([, v]) => typeof v === "string")
    .map(([k, v]) => `export ${k}=${JSON.stringify(v)}`);
  const envShPath = join(homeDir, ".petbox", "env.sh");
  // In production ~/.petbox/ already exists by this point (writeKeyToStore runs first in
  // main()'s step 4), but mkdirSync recursive is a harmless no-op then — and it makes this
  // module safe to call standalone (e.g. from tests against a bare tmp dir).
  mkdirSync(join(homeDir, ".petbox"), { recursive: true });
  writeFileSync(envShPath, "# Generated by petbox-wire from ~/.petbox/keys.json — do not edit.\n" + lines.join("\n") + "\n", "utf8");
  try {
    chmodSync(envShPath, 0o600);
  } catch {
    /* best-effort */
  }

  const marker = "# petbox-wire";
  const sourceLine = `[ -f "$HOME/.petbox/env.sh" ] && . "$HOME/.petbox/env.sh" ${marker}`;
  const profiles = [".profile", ".bashrc", ".zshenv"].map((f) => join(homeDir, f));
  let sourced = false;
  for (const p of profiles) {
    if (!existsSync(p)) continue;
    const content = readFileSync(p, "utf8");
    if (!content.includes(marker)) appendFileSync(p, `\n${sourceLine}\n`, "utf8");
    sourced = true;
  }
  if (!sourced) writeFileSync(profiles[0], sourceLine + "\n", "utf8");

  // zsh always sources ~/.zshenv for EVERY shell (login or not, interactive or not) — unlike
  // .profile/.bashrc, which bash only sources under specific conditions. macOS ships zsh as the
  // default shell and a fresh account typically has none of the three files, so the fallback
  // above (which only ever creates .profile) would silently leave zsh unwired. Guarantee the
  // marker lands in .zshenv too, independent of whichever profile the loop above touched.
  const zshenvPath = profiles[2];
  if (!existsSync(zshenvPath)) writeFileSync(zshenvPath, sourceLine + "\n", "utf8");

  return envShPath;
}
