// POSIX half of persistKeyForAgents (see wire.ts) — split into its own side-effect-free module
// (no top-level main()) so it can be imported directly by tests without triggering the CLI.
// wire.ts is NOT import-safe: it runs main() at module top level (see bin/petbox-wire.js), so a
// test must not `import` it — this file exists to give the logic a testable home.

import { appendFileSync, chmodSync, existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { petboxDir, petboxKeysJsonPath } from "./petbox-dir.ts";
import { inspectKeyStoreEntry, UnresolvedEnvRefError } from "./registry.ts";

function readJson(path: string): any {
  try {
    return JSON.parse(readFileSync(path, "utf8"));
  } catch {
    return null;
  }
}

// Regenerate <homeDir>/.petbox/env.sh from the whole key store and ensure a login shell will
// source it. Parameterized on homeDir (instead of reading os.homedir() directly) so tests can
// point it at a throwaway tmp dir rather than touching the real $HOME. Returns the path written,
// for the caller's log message.
//
// keys-json-supports-env-var-references: env.sh must always end up with the REAL literal value,
// never the reference text. A keys.json entry can now be a $VAR/${VAR} reference — resolve each
// one via inspectKeyStoreEntry (same logic as registry.ts's live read path) before writing it
// out. Writing "${VAR}" itself into this file would be silently self-correcting only by luck
// (bash/zsh both variable-expand "${VAR}" inside a double-quoted string at SOURCE time, so it
// would happen to work whenever the sourcing shell's own environment already has VAR set — and
// silently export an EMPTY string otherwise). That accidental behavior is exactly the kind of
// silent placeholder-reaches-a-consumer failure this card exists to rule out, so this throws
// UnresolvedEnvRefError instead of ever writing the raw reference text.
export function persistKeyForAgentsPosix(homeDir: string, project = "(unknown project)"): string {
  const store = readJson(petboxKeysJsonPath(homeDir)) ?? {};
  const lines: string[] = [];
  for (const k of Object.keys(store)) {
    if (typeof store[k] !== "string") continue;
    const entry = inspectKeyStoreEntry(k, homeDir);
    if (entry.kind === "absent") continue; // can't happen for a key just read from this same store, but harmless
    if (entry.kind === "literal") {
      lines.push(`export ${k}=${JSON.stringify(entry.value)}`);
    } else if (entry.resolved !== null) {
      lines.push(`export ${k}=${JSON.stringify(entry.resolved)}`);
    } else {
      throw new UnresolvedEnvRefError(k, entry.refVar, project);
    }
  }
  const envShPath = join(petboxDir(homeDir), "env.sh");
  // In production ~/.petbox/ already exists by this point (writeKeyToStore runs first in
  // main()'s step 4), but mkdirSync recursive is a harmless no-op then — and it makes this
  // module safe to call standalone (e.g. from tests against a bare tmp dir).
  mkdirSync(petboxDir(homeDir), { recursive: true });
  writeFileSync(envShPath, "# Generated by petbox-wire from ~/.petbox/keys.json — do not edit.\n" + lines.join("\n") + "\n", "utf8");
  try {
    chmodSync(envShPath, 0o600);
  } catch {
    /* best-effort */
  }

  const marker = "# petbox-wire";
  // Deliberately a literal, NOT built from petboxDir(): this is POSIX shell TEXT, sourced by the
  // target login shell at ITS OWN runtime via ITS OWN $HOME — not a Node path resolved here. See
  // petbox-dir.ts's module comment for why this carve-out is intentional.
  const sourceLine = `[ -f "$HOME/.petbox/env.sh" ] && . "$HOME/.petbox/env.sh" ${marker}`;
  const profilePath = join(homeDir, ".profile");
  const bashrcPath = join(homeDir, ".bashrc");
  const zshenvPath = join(homeDir, ".zshenv");
  const profiles = [profilePath, bashrcPath, zshenvPath];
  let sourced = false;
  for (const p of profiles) {
    if (!existsSync(p)) continue;
    const content = readFileSync(p, "utf8");
    if (!content.includes(marker)) appendFileSync(p, `\n${sourceLine}\n`, "utf8");
    sourced = true;
  }
  if (!sourced) writeFileSync(profilePath, sourceLine + "\n", "utf8");

  // zsh always sources ~/.zshenv for EVERY shell (login or not, interactive or not) — unlike
  // .profile/.bashrc, which bash only sources under specific conditions. macOS ships zsh as the
  // default shell and a fresh account typically has none of the three files, so the fallback
  // above (which only ever creates .profile) would silently leave zsh unwired. Guarantee the
  // marker lands in .zshenv too, independent of whichever profile the loop above touched.
  if (!existsSync(zshenvPath)) writeFileSync(zshenvPath, sourceLine + "\n", "utf8");

  return envShPath;
}
